controller:
  adminUser: admin
  adminPassword: admin123
  serviceType: ClusterIP
  serviceType: ClusterIP
  installPlugins: []
  installLatestPlugins: false
  installLatestSpecifiedPlugins: false
  resources:
    requests:
      cpu: "200m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  persistence:
    enabled: false
    storageClass: ""
