{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .repoURL | quote }}
    targetRevision: {{ .targetRevision | quote }}
    path: {{ .path | quote }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .namespace | quote }}
  syncPolicy:
    {{- toYaml .syncPolicy | nindent 4 }}
---
{{- end }}
